// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';

export function GetStatus():Promise<Record<string, any>>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ProcessKeyPress(arg1:string):Promise<void>;
