// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['OnSecondInstanceLaunch'](arg1);
}

export function ProcessKeyPress(arg1) {
  return window['go']['main']['App']['ProcessKeyPress'](arg1);
}
